---
- hosts: webb
  tasks:
    - name: Make sure the latest version of the Apache package is installed.
      package:
        name: httpd
        state: latest
      notify: restart apache

    - name: Start Apache at boot.
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Create website directory
      file:
        path: /var/www/example.org
        state: directory
        owner: apache
        group: apache

    - name: Copy index.html to the website directory
      copy:
        src: filer/index.html
        dest: /var/www/example.org/index.html

    - name: Define a vhost.
      copy:
        src: "filer/my_vhost.conf"
        dest: "/etc/httpd/conf.d/my_vhost.conf"
      notify: restart apache

    - name: Create 3 users.
      user:
        name: "{{ item }}"
      loop:
        - bert
        - earnie
        - cookie-monster

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
